apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: users-service
spec:
  selector:
    app: users-service
  ports:
    - protocol: "TCP"
      port: 9092 # The port that the service is running on in the cluster
      targetPort: 9092 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: users-service
spec:
  selector:
    matchLabels:
      app: users-service
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: users-service # Image that will be used inside the container in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092 # The port that the container is running on in the cluster